name: CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 20

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Decode Keystore
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}

        run: |
          echo -n $KEYSTORE | base64 --decode > keystore.jks

      - name: Build Release bundle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          ./gradlew bundleProductionRelease --stacktrace

      - name: Get release file aab path
        id: releaseAab
        run: echo "aabfile=$(find app/build/outputs/bundle/productionRelease/*.aab)" >> $GITHUB_OUTPUT

      - name: Upload release bundle artifact
        uses: actions/upload-artifact@v3
        with:
           name: release-artifacts
           path: ${{ steps.releaseAab.outputs.aabfile }}

      - name: Save service-account.json
        run: echo "${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}" | base64 --decode > service-account.json

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service-account.json
          packageName: net.einsa.lotta
          releaseFiles: ${{ steps.releaseAab.outputs.aabfile }}
          track: qa
          status: draft
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib
